import{a as P,S as C,i as g}from"./assets/vendor-Dy2ZTtfi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const O="https://pixabay.com/api/",$="50822348-bdabbbb26163a7cc5d8d36121";async function p(o,t){const s=new URLSearchParams({key:$,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t});return(await P.get(`${O}?${s}`)).data}const q={overlay:!0,nav:!0,captionsData:"alt",captionDelay:250},B=new C(".gallery a",q),f=document.querySelector(".gallery"),m=document.querySelector(".loader"),d=document.querySelector(".more-btn");m||console.warn("⚠️ Loader element not found in the DOM!");f||console.warn("⚠️ Gallery element not found in the DOM!");d||console.warn("⚠️ Button Load more element not found in the DOM!");function L(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:n,comments:S,downloads:M})=>`<li class="gallery-card">
        <a href="${a}">
        <img class="gallery-photo" src="${s}" alt="${e.split(",").slice(0,10).join(",")}"/>
        </a>
        <ul class="card-list">
        <li><h3>Likes</h3><p>${r}</p></li>
        <li><h3>Viwes</h3><p>${n}</p></li>
        <li><h3>Comments</h3><p>${S}</p></li>
        <li><h3>Downloads</h3><p>${M}</p></li>
        </ul>
        </li>
    `).join("");f.insertAdjacentHTML("beforeend",t),B.refresh()}function D(){f.innerHTML=""}function w(){m.classList.remove("hidden")}function b(){m.classList.add("hidden")}function v(){d.classList.remove("hidden")}function h(){d.classList.add("hidden")}const x=document.querySelector(".form");x.addEventListener("submit",E);let c=null,l=1,u=null,y;async function E(o){if(o.preventDefault(),c=o.target.elements["search-text"].value.toLowerCase().trim(),!c){i({message:"Please, enter word for search!"});return}D(),h(),w(),l=1,u=null;try{const t=await p(c,l),s=t.hits;if(s.length===0){i({message:"Sorry, there are no images matching your search query. Please try again!"});return}L(s),u=Math.ceil(t.totalHits/s.length)}catch(t){g.show({message:t.message})}finally{b()}u>1?v():i({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"yellow",messageColor:"black"})}d.addEventListener("click",k);async function k(){l+=1,h();try{w();const o=await p(c,l);L(o.hits),b();let t=document.querySelector(".gallery-card");if(t&&(y=t.getBoundingClientRect(),window.scrollBy({top:y.height*2,behavior:"smooth"})),l===u){i({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"yellow",messageColor:"black"}),h();return}v()}catch(o){i({message:o.message})}}function i({message:o="",backgroundColor:t="red",messageColor:s="white",position:a="topRight",maxWidth:e=380,messageSize:r="16",className:n="my-toast"}){g.show({message:o,messageColor:s,backgroundColor:t,position:a,maxWidth:e,messageSize:r,class:n})}
//# sourceMappingURL=index.js.map
