import{a as P,S as $,i as g}from"./assets/vendor-Dy2ZTtfi.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const n of o.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=s(e);fetch(e.href,o)}})();const q="https://pixabay.com/api/",B="50822348-bdabbbb26163a7cc5d8d36121";async function p(r,t){const s=new URLSearchParams({key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t});return(await P.get(`${q}?${s}`)).data}const C={overlay:!0,nav:!0,captionsData:"alt",captionDelay:250},O=new $(".gallery a",C),h=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".more-btn");m||console.warn("⚠️ Loader element not found in the DOM!");h||console.warn("⚠️ Gallery element not found in the DOM!");f||console.warn("⚠️ Button Load more element not found in the DOM!");function L(r){const t=r.map(({webformatURL:s,largeImageURL:a,tags:e,likes:o,views:n,comments:v,downloads:M})=>`<li class="gallery-card">
        <a href="${a}">
        <img class="gallery-photo" src="${s}" alt="${e.split(",").slice(0,10).join(",")}"/>
        </a>
        <ul class="card-list">
        <li><h3>Likes</h3><p>${o}</p></li>
        <li><h3>Views</h3><p>${n}</p></li>
        <li><h3>Comments</h3><p>${v}</p></li>
        <li><h3>Downloads</h3><p>${M}</p></li>
        </ul>
        </li>
    `).join("");h.insertAdjacentHTML("beforeend",t),O.refresh()}function D(){h.innerHTML=""}function b(){m.classList.remove("hidden")}function w(){m.classList.add("hidden")}function S(){f.classList.remove("hidden")}function d(){f.classList.add("hidden")}const x=document.querySelector(".form"),E=document.querySelector(".more-btn");x.addEventListener("submit",k);let c=null,l=1,u=null,y;async function k(r){if(r.preventDefault(),c=r.target.elements["search-text"].value.toLowerCase().trim(),!c){i({message:"Please, enter word for search!"});return}D(),d(),b(),l=1,u=null;try{const t=await p(c,l),s=t.hits;if(s.length===0){i({message:"Sorry, there are no images matching your search query. Please try again!"});return}L(s),u=Math.ceil(t.totalHits/s.length)}catch(t){g.show({message:t.message})}finally{w()}l===u?i({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"yellow",messageColor:"black"}):S()}E.addEventListener("click",A);async function A(){l+=1,d();try{b();const r=await p(c,l);L(r.hits);let t=document.querySelector(".gallery-card");if(t&&(y=t.getBoundingClientRect(),window.scrollBy({top:y.height*2,behavior:"smooth"})),l===u){i({message:"We're sorry, but you've reached the end of search results.",backgroundColor:"yellow",messageColor:"black"}),d();return}S()}catch(r){i({message:r.message})}finally{w()}}function i({message:r="",backgroundColor:t="red",messageColor:s="white",position:a="topRight",maxWidth:e=380,messageSize:o="16",className:n="my-toast"}){g.show({message:r,messageColor:s,backgroundColor:t,position:a,maxWidth:e,messageSize:o,class:n})}
//# sourceMappingURL=index.js.map
